### PR TITLE
Package trace.

### PR DESCRIPTION
**Pull request by ejholmes**
Not necessarily going to merge this, just opening it up for discussion. Package trace composes package logger and package reporter as one. It's meant to be used like a logger but the third argument takes an `error`. If the `error` is non nil, it's reported using the embedded reporter.

Might be better to add a Logger implementation that checks for an `err` key in the log pairs.

### CODE REVIEW

**Comment by phobologic** [comment]
So I took a look - not sure I have an opinion one way or another, unfortunately, so basically this comment is useless :)  I think I'd need to see it in action, or at least discuss it with you more to better understand your usecase.

**Comment by bmarini** [comment]
That is kinda nice. There is definitely the need to use the reporter to report errors that aren't panic's. On a side note, I was thinking the error middleware could benefit from including the ctx in the func signature so you could report all errors from there...

**Comment by ejholmes** [comment]
I discovered some goodies in [docker/distribution](https://github.com/docker/distribution/blob/master/context/trace.go#L39). It might be nice to do something along those lines, so tracing can also give you the name of the function, timing, etc.

**Comment by ejholmes** [comment]
Ok, still a WIP but I think what I have in here now is going in the right direction. I pulled in some concepts from docker/distribution so that we inject the http.Request into the context, and the logger can now optionally implement an interface for creating a child logger, this allows the trace package to be used like this:

```go
ctx, done := trace.Trace(ctx)
defer func() { done(err, "did something", "thing", thing) }
```

This will log a log line to the embedded logger with the function it was called from, file, line number, error, the duration of the function call and also the trace id of the parent function if present.

```
t=2015-05-18T16:41:47+0000 lvl=info msg="submitting app" request_id=48bedb25-d06a-4898-9a39-b25fb726bd37 trace.id=eada9ebc-be5e-4b57-aee9-204447c837d6 trace.func=github.com/remind101/empire/empire/pkg/service.(*LoggedManager).Submit trace.file=/go/src/github.com/remind101/empire/empire/pkg/service/logger.go trace.line=25 trace.duration=4.06958837s app=92289c36-8644-4900-8850-7ec3578ec368
```

Thinking I'll pull this branch into empire and tweak and polish things before merging.

/cc @sanjayprabhu

**Comment by ejholmes** [comment]
This is pretty old. I think using something like [pkg/errors](https://github.com/pkg/errors) is a better approach.

**Pull request closed without merging**
